blank_issues_enabled: true
contact_links:
    - name: 📃 Open Mapping at Facebook
      url: https://github.com/facebookmicrosites/Open-Mapping-At-Facebook
      about: Visit this site to learn more about how Meta maps on OSM.
    - name: 💫 New v2 Architecture - about the WebGL rewrite
      url: https://github.com/facebookincubator/Rapid/discussions/481
      about: The Rapid team is in the process of rewriting the entire Rapid renderer in WebGL. Read about it here!
    - name: 🚀 Talk with us on Slack
      url: osmus.slack.com
      about: Come find us in the #mapwithai_feedback channel!